# Generated by Django 3.1.5 on 2021-02-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_auto_20210206_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
