# Generated by Django 3.1.5 on 2021-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='link',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AddField(
            model_name='webpage',
            name='set_name',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AddField(
            model_name='webpage',
            name='tell',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='about',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='fb',
            field=models.CharField(default='.,', max_length=30),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='tw',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='yt',
            field=models.CharField(default='.', max_length=30),
        ),
    ]
